
### Create a new document
POST https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "Buy a Large Coffee",
  "important": true
}

### Create a new document
POST https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "Drink Coffee",
  "important": true,
  "completed": true
}

### Create a new document
POST https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "Go home and sleep",
  "important": false
}


### GET All documents
GET https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo.json

### GET One document by key
GET https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo/-NQc8qUvjV4-K9m4MrZj.json

### UPDATE document - will replace all properties with the properties in the request body - if you miss a property it will be removed
PUT https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo/-NQc986GF3f3ABlIIJcq.json
Content-Type: application/json

{
  "task": "Go home and rest",
  "important": true
}

### DELETE document - use this if you want to delete a document
DELETE https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo/-NQc8OGTsjBvljVDALQ3.json


### PATCH document - use this if you want to update some of the properties but not all of them
PATCH https://dmit2015-1222-swu-demos-default-rtdb.firebaseio.com/Todo/-NQc8qUvjV4-K9m4MrZj.json
Content-Type: application/json

{
  "task": "Drink Latte"
}