package dmit2015.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;

@Entity
@Getter @Setter
@NoArgsConstructor
public class TodoItem implements Serializable {

    private String username;

    @Id                 // This is the primary key field
    @GeneratedValue(strategy = GenerationType.IDENTITY)     // This primary key field is generated by the database
    @Column(name = "todoId")
    private Long id;

    @NotBlank(message = "Name field value is required.")
    @Column(nullable = false, length = 64)
    private String name;

    private boolean complete;

//    @Version
//    private Integer version;
//
//    @Column(nullable = false)
//    private LocalDateTime createTime;
//
//    private LocalDateTime updateTime;

//    @PrePersist
//    private void beforePersist() {
//        createTime = LocalDateTime.now();
//    }
//
//    @PreUpdate
//    private void beforeUpdate() {
//        updateTime = LocalDateTime.now();
//    }

    public TodoItem(Long id, String name, boolean complete) {
        this.id = id;
        this.name = name;
        this.complete = complete;
    }

}