### Get all TodoItems
GET http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems

### Get a single TodoItem with an id of 1
GET http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems/1

### POST a new TodoItem with valid data
POST http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems
Content-Type: application/json

{
  "name": "Start DMIT2015 Assignment 3",
  "complete": false
}

### Post a new TodoItem with invalid data
POST http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems
Content-Type: application/json

{
  "name": "     ",
  "complete": false
}

### Get a single TodoItem with an id of 4
GET http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems/4

### Update TodoItem with an id of 4 with valid data
PUT http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems/4
Content-Type: application/json

{
  "id": 4,
  "name": "Commit DMIT2015 Assignment 3",
  "complete": true,
  "version": 0
}

### Delete an TodoItem with an id of 2
DELETE http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems/2

### Delete an TodoItem with an id of 4
DELETE http://localhost:8080/dmit2015-jaxrs-backend/restapi/TodoItems/4
